workflows:
  ios-debug:
    name: iOS Debug Build
    max_build_duration: 60
    environment:
      xcode: 16.4
      vars:
        DERIVED_DATA: /Users/builder/clone/DerivedData
    scripts:
      - name: Install dependencies
        script: |
          brew install wget || true
          gem install cocoapods || true
          pod install || true
      - name: Build for iOS Simulator (no code signing)
        script: |
          xcodebuild \
            -project ios/Audiobooks.xcodeproj \
            -scheme Audiobooks \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.5" \
            -derivedDataPath "$DERIVED_DATA" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build
      - name: Package .app
        script: |
          APP_PATH=$(find "$DERIVED_DATA/Build/Products" -type d -name "*.app" | head -n 1 || true)
          if [ -z "$APP_PATH" ]; then
            echo "No .app found, build likely failed."
            exit 1
          fi
          echo "App at: $APP_PATH"
          mkdir -p "$CM_ARTIFACTS/app"
          cp -R "$APP_PATH" "$CM_ARTIFACTS/app/"
    artifacts:
      - app/**
    publishing:
      email:
        recipients:
          - your@email.com
