workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      vars:
        XCODE_WORKSPACE: "Audiobooks.xcworkspace"
        XCODE_SCHEME: "Audiobooks"
      ios_signing:
        certificates:
          - SSS
        provisioning_profiles:
          - audiobooks_appstore_profile
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build ipa for App Store
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
