workflows:
  ios-debug:
    name: iOS Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      xcode: 16.4
      vars:
        PROJECT_DIR: "ios"
        PROJECT_FILE: "Audiobooks.xcodeproj"
        SCHEME: "Audiobooks"
        DERIVED_DATA: "$CM_BUILD_DIR/DerivedData"

    scripts:
      - name: Install tools
        script: |
          brew install xcodegen || true
          gem install xcpretty --no-document

      - name: Generate Xcode project
        script: |
          cd "$PROJECT_DIR"
          xcodegen generate
          ls -la

      - name: List schemes
        script: |
          cd "$PROJECT_DIR"
          xcodebuild -list -project $PROJECT_FILE || true

      - name: Build for iOS Simulator
        script: |
          cd "$PROJECT_DIR"
          xcodebuild \
            -project $PROJECT_FILE \
            -scheme "$SCHEME" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.5" \
            -derivedDataPath "$DERIVED_DATA" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build | xcpretty

      - name: Package .app
        script: |
          APP_PATH="$DERIVED_DATA/Build/Products/Debug-iphonesimulator/$SCHEME.app"
          echo "Looking for app at $APP_PATH"
          ls -R "$DERIVED_DATA" || true
          if [ ! -d "$APP_PATH" ]; then
            echo "No .app found, build failed."
            exit 1
          fi
          mkdir -p "$CM_ARTIFACTS/app"
          cp -R "$APP_PATH" "$CM_ARTIFACTS/app/"

    artifacts:
      - $CM_ARTIFACTS/app/*.app
