workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      vars:
        SCHEME: "Audiobooks"
        DERIVED_DATA: "$CM_BUILD_DIR/DerivedData"
      xcode: latest

    scripts:
      - name: Build for iOS Simulator (no code signing)
        script: |
          xcodebuild \
            -project ios/Audiobooks.xcodeproj \
            -scheme "$SCHEME" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.5" \
            -derivedDataPath "$DERIVED_DATA" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            build | xcpretty

      - name: Package .app
        script: |
          APP_PATH=$(find "$DERIVED_DATA/Build/Products" -type d -name "*.app" | head -n 1 || true)
          if [ -z "$APP_PATH" ]; then
            echo "No .app found, build failed."
            exit 1
          fi
          echo "App at: $APP_PATH"
          mkdir -p "$CM_ARTIFACTS/app"
          cp -R "$APP_PATH" "$CM_ARTIFACTS/app/"

    artifacts:
      - app/*.app
