workflows:
  ios-debug:
    name: iOS Debug Build
    max_build_duration: 60
    environment:
      xcode: 16.4
      vars:
        SCHEME: "Audiobooks"
        PROJECT_PATH: "ios/Audiobooks.xcodeproj"
        DERIVED_DATA: "$CM_BUILD_DIR/DerivedData"
    scripts:
      - name: Install dependencies
        script: |
          brew install xcpretty || true
      - name: Build for iOS Simulator (no code signing)
        script: |
          xcodebuild \
            -project "$PROJECT_PATH" \
            -scheme "$SCHEME" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.5" \
            -derivedDataPath "$DERIVED_DATA" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build | xcpretty
      - name: Package .app
        script: |
          APP_PATH="$DERIVED_DATA/Build/Products/Debug-iphonesimulator/$SCHEME.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "No .app found at $APP_PATH, build failed."
            ls -R "$DERIVED_DATA/Build" || true
            exit 1
          fi
          echo "App at: $APP_PATH"
          mkdir -p "$CM_ARTIFACTS/app"
          cp -R "$APP_PATH" "$CM_ARTIFACTS/app/"
    artifacts:
      - $CM_ARTIFACTS/app/*.app
