workflows:
  ios-appstore:
    name: iOS App Store
    environment:
      ios_signing:
        certificates:
          - SSS
        provisioning_profiles:
          - audiobooks_appstore_profile
    integrations:
      app_store_connect: Coda3
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build ipa for App Store
        script: |
          xcode-project build-ipa \
            --workspace ios/Audiobooks.xcworkspace \
            --scheme Audiobooks
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
