workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      xcode: 16.4
      cocoapods: default
    integrations:
      app_store_connect: integration
    scripts:
      - name: Install dependencies
        script: |
          cd ios
          pod install --repo-update
      - name: Build app for release
        script: |
          xcode-project build-ipa \
            --project ios/Audiobooks.xcodeproj \
            --scheme Audiobooks \
            --export-options-plist ios/export_options.plist \
            --archive-flags="-allowProvisioningUpdates DEVELOPMENT_TEAM=CW6VS28729"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
