workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      xcode: 16.4
    integrations:
      app_store_connect: integration

    scripts:
      - name: Build app for release
        script: |
          xcode-project build-ipa \
            --project Audiobooks.xcodeproj \
            --scheme Audiobooks \
            --archive-flags="-allowProvisioningUpdates"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
