workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      xcode: 16.4
    integrations:
      app_store_connect: integration
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --bundle-id com.serhiitkachuk.Audiobooks \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build app with xcodebuild
        script: |
          cd ios
          xcodebuild archive \
            -project Audiobooks.xcodeproj \
            -scheme Audiobooks \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            -archivePath ../build/ios/xcarchive/Audiobooks.xcarchive \
            DEVELOPMENT_TEAM=CW6VS28729 \
            CODE_SIGN_STYLE=Automatic \
            | xcpretty
          xcodebuild -exportArchive \
            -archivePath ../build/ios/xcarchive/Audiobooks.xcarchive \
            -exportOptionsPlist export_options.plist \
            -exportPath ../build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
