workflows:
  ios-debug:
    name: iOS Simulator Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Build for iOS Simulator (no code signing)
        script: |
          xcodebuild \
            -project ios/Audiobooks.xcodeproj \
            -scheme Audiobooks \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.5" \
            -derivedDataPath DerivedData \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build
    artifacts:
      - DerivedData/Build/Products/Debug-iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - 7520960@gmail.com
