workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      xcode: 16.4
    integrations:
      app_store_connect: integration
    scripts:
      - name: Clean workspace
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf build

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --bundle-id com.serhiitkachuk.Audiobooks \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build app for release
        script: |
          xcodebuild \
            -project ios/Audiobooks.xcodeproj \
            -scheme Audiobooks \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            -archivePath build/ios/xcarchive/Audiobooks.xcarchive \
            DEVELOPMENT_TEAM=CW6VS28729 \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="audiobooks_appstore_profile" \
            -allowProvisioningUpdates \
            archive

          xcodebuild \
            -exportArchive \
            -archivePath build/ios/xcarchive/Audiobooks.xcarchive \
            -exportOptionsPlist ios/export_options.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
