      - name: Build for iOS Simulator (no code signing)
        script: |
          cd "$PROJECT_DIR"
          set -o pipefail
          if [ -d "Audiobooks.xcodeproj" ]; then
            xcodebuild \
              -project Audiobooks.xcodeproj \
              -scheme "$SCHEME" \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
              -derivedDataPath "$DERIVED_DATA" \
              CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
              build
          elif [ -d "Audiobooks.xcworkspace" ]; then
            xcodebuild \
              -workspace Audiobooks.xcworkspace \
              -scheme "$SCHEME" \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
              -derivedDataPath "$DERIVED_DATA" \
              CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
              build
          else
            echo "No project or workspace to build."
            exit 1
          fi
