workflows:
  ios-appstore:
    name: iOS App Store
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      ios_signing:
        certificates:
          - SSS
        provisioning_profiles:
          - audiobooks_appstore_profile
    integrations:
      app_store_connect: Coda3
    scripts:
      - name: Build ipa for App Store
        script: |
          xcode-project build-ipa \
            --project ios/Audiobooks.xcodeproj \
            --scheme Audiobooks
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
