workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        PROJECT_DIR: "ios"
        SCHEME: "Audiobooks"
      xcode: latest

    scripts:
      - name: Install build tools
        script: |
          brew update
          brew install xcodegen || true
          gem install fastlane --no-document

      - name: Generate Xcode project from project.yml
        script: |
          cd "$PROJECT_DIR"
          xcodegen generate
          ls -la

      - name: Build for iOS Simulator (no code signing)
        script: |
          cd "$PROJECT_DIR"
          xcodebuild \
            -project Audiobooks.xcodeproj \
            -scheme "$SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            build | xcpretty

      - name: Debug: list build outputs
        script: |
          echo "Searching for .app bundles..."
          find $CM_BUILD_DIR -type d -name "*.app" || true

      - name: Package .app
        script: |
          APP_PATH=$(find $CM_BUILD_DIR -type d -name "*.app" | head -n 1)
          echo "App at: $APP_PATH"
          mkdir -p "$CM_ARTIFACTS"
          cp -R "$APP_PATH" "$CM_ARTIFACTS/"

    artifacts:
      - "*.app"
