platform :ios, '13.0'

project '../Audiobooks.xcodeproj'

target 'Audiobooks' do
  use_frameworks!
  use_modular_headers!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Purchases'
end
