platform :ios, '13.0'

use_frameworks!
use_modular_headers!

target 'Audiobooks' do
  project 'ios/Audiobooks.xcodeproj'

  pod 'Alamofire', '~> 5.6'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'SDWebImage', '~> 5.0'
end
