name: Audiobooks
options:
  bundleIdPrefix: com.serhiitkachuk
configs:
  Debug: debug
  Release: release
targets:
  Audiobooks:
    type: application
    platform: iOS
    sources: .
    bundleId: com.serhiitkachuk.Audiobooks
    deploymentTarget: "16.0"
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_NAME: Audiobooks
        DEVELOPMENT_TEAM: CW6VS28729
