name: Audiobooks
options:
  bundleIdPrefix: com.serhiitkachuk
  deploymentTarget:
    iOS: '13.0'
targets:
  Audiobooks:
    type: application
    platform: iOS
    sources: .
    resources: []
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.serhiitkachuk.Audiobooks
      INFO_PLIST_FILE: Info.plist
      SWIFT_VERSION: 5.0
