name: Audiobooks
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"

targets:
  Audiobooks:
    type: application
    platform: iOS
    sources:
      - Audiobooks
    resources:
      - Audiobooks/Assets.xcassets
      - Audiobooks/Info.plist
    settings:
      base:
        INFOPLIST_FILE: Audiobooks/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.audiobooks
        SWIFT_VERSION: 5.0
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        TARGETED_DEVICE_FAMILY: "1,2"
    scheme:
      testTargets: []

  AudiobooksTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - AudiobooksTests
    dependencies:
      - target: Audiobooks
